'use client'

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, {useState} from "react";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });


// @ts-ignore
// export const metadata: Metadata = {
//   title: "Gra w trzy karty",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [active, setActive] = useState(false);
    const handleClick = () => {
        setActive((prevActive) => !prevActive);
    };
  return (
    <html lang="en">
    <head>
       <title>Gra w trzy karty</title>
    </head>
      <body className={inter.className + ' bg-green-800'}>
      <Header onClick={handleClick} active={active}/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
